name: Test and Coverage

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      DB_CONNECTION: sqlite

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Copy .env.test to environment variables
        run: cp .env.test .env

      - name: Create tmp directory
        run: mkdir tmp

      - name: Run tests with coverage
        run: pnpm run test:coverage

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage
