name: Deploy API 3 to EC2

on:
  push:
    branches:
      - beta
      - main
      - feat/ncm

    paths:
      - "apps/api/v3/**"
      - ".github/workflows/deploy-api3.yml"

  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "apps/api/v3/**"
      - ".github/workflows/deploy-api3.yml"

env:
  BRANCH: ${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    # env:
    #   TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #   TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    strategy:
      matrix:
        ec2_host: ${{ fromJson(github.ref_name  == 'beta' && vars.EC2_DEPLOY_HOSTS_1 || vars.EC2_DEPLOY_HOSTS_2) }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm install --filter=api-v3
          pnpm turbo prune api-v3

      - name: Build the API
        run: |
          cd out
          pnpm install
          pnpm build

      - name: Package application
        run: |
          mv out monorepo
          tar -czf deploy.tar.gz monorepo

      - name: Deploy to EC2 ${{ env.BRANCH }}
        env:
          EC2_USER: ${{ vars.EC2_USER_2 }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
          PROJECT_PATH: ${{ env.BRANCH == 'beta' && vars.API3_BETA_PATH || vars.API3_PROD_PATH }}
          ENV_PATH: ${{ env.BRANCH == 'beta' && vars.API3_BETA_ENV_HOST || vars.API3_PROD_ENV_HOST }}
        run: |
          echo "$EC2_KEY" > private_key.pem
          chmod 600 private_key.pem

          mkdir -p ~/.ssh

          ssh-keyscan -H ${{ matrix.ec2_host }} >> ~/.ssh/known_hosts

          scp -i private_key.pem deploy.tar.gz $EC2_USER@${{ matrix.ec2_host }}:$PROJECT_PATH

          ssh -i private_key.pem $EC2_USER@${{ matrix.ec2_host }} << 'EOF'
            cd ${{ env.PROJECT_PATH }}
            tar -xzf deploy.tar.gz
            rm deploy.tar.gz
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
            cd monorepo/apps/api/v3
            scp ${{ secrets.EC2_ENV_HOST }}:${{ env.ENV_PATH }} .env
            cd build
            ln -s ../.env .env
            cd ..
            pm2 start ${{ env.BRANCH == 'beta' && '../ecosystem_beta.config.cjs' || '../ecosystem.config.cjs' }}
          EOF

          rm private_key.pem
