name: Deploy Site to EC2

on:
  push:
    branches:
      - beta
      - main

    paths:
      - "apps/site/**"
      - ".github/workflows/deploy-site.yml"

  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "apps/site/**"
      - ".github/workflows/deploy-site.yml"

env:
  BRANCH: ${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ec2_host: ${{ fromJson(github.ref_name  == 'beta' && vars.EC2_DEPLOY_HOSTS_1 || vars.EC2_DEPLOY_HOSTS) }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install NVM
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 20
          nvm use 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          npm install -g turbo
          pnpm turbo prune site

      - name: Build application
        run: |
          cd out
          pnpm install

      - name: Package application
        run: |
          tar -czf deploy.tar.gz --exclude='node_modules' -C out/apps/site .

      - name: Deploy to EC2 ${{ env.BRANCH }}
        env:
          EC2_USER: ${{ vars.EC2_USER_1 }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
          PROJECT_PATH: ${{ env.BRANCH == 'beta' && vars.SITE_BETA_PATH || vars.SITE_PROD_PATH }}
          ENV_PATH: ${{ env.BRANCH == 'beta' && vars.SITE_BETA_ENV_HOST || vars.SITE_PROD_ENV_HOST }}
        run: |
          echo "$EC2_KEY" > private_key.pem
          chmod 600 private_key.pem

          mkdir -p ~/.ssh

          ssh-keyscan -H ${{ matrix.ec2_host }} >> ~/.ssh/known_hosts

          scp -i private_key.pem deploy.tar.gz $EC2_USER@${{ matrix.ec2_host }}:$PROJECT_PATH

          ssh -i private_key.pem $EC2_USER@${{ matrix.ec2_host }} << 'EOF'
            cd ${{ env.PROJECT_PATH }}
            sudo rm -rf public_html/*
            tar -xzf deploy.tar.gz -C public_html
            ls -la public_html
            rm deploy.tar.gz
            cd public_html
            scp ${{ secrets.EC2_ENV_HOST }}:${{ env.ENV_PATH }} .env
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
            npm install --ignore-scripts
            pm2 start ${{ env.BRANCH == 'beta' && 'ecosystem_beta.config.cjs' || 'ecosystem.config.cjs' }}
          EOF

          rm private_key.pem
