name: Build/release WhatsMenu Desktop

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  make:
    name: Make artifacts
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set NPM Cache Directory
        run: npm config set cache C:\npm\cache --global

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run make

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: squirrel-windows
          path: ./out/make/squirrel.windows/ia32

  release:
    needs: make
    runs-on: windows-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: squirrel-windows
          path: ./out/make/squirrel.windows/ia32

      - name: List files
        run: ls ./out/make/squirrel.windows/ia32

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
      
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/make/squirrel.windows/ia32
          asset_name: teste
          asset_content_type: application/octet-stream